### ISSUE TITLE
Large text's ::before elements overlapping horizontal scrollbars

### ISSUE THREAD

**Issue by MrPerux** [TFNS/CTFNote#176] opened 2022-08-20 22:14 UTC
When large text like `## *text*` follows a code segment with horizontal scrolling, the `::before` pseudo-element has can have a large enough padding to overlap the scrollbar. This overlap is invisible, but makes the user unable to interact with the scrollbar via the mouse.

Example:
![image](https://user-images.githubusercontent.com/31393019/185767773-48a5648a-2fb0-4f46-b220-27e3977dc44d.png)

Produced by: (without the backslashes)
```markdown
\```
This is some code. This is some code. This is some code. This is some code. 
\```

## This is text
```

**Comment by JJ-8** [comment] 2022-08-23 09:35
Thank you for your bug report @MrPerux!

Is this an issue within the preview (or split screen) mode of writing a note for a task? If so, this is an issue in Hedgedoc itself and we can not fix this in CTFNote. Also, this won't be fixed by the Hedgedoc team since they are working on Hedgedoc v2 and won't fix small issues like this in Hedgedoc v1.
Moreover, I can not reproduce this issue on Linux in Firefox so maybe this issue is OS or browser specific?

**Comment by JJ-8** [comment] 2022-12-05 09:27
Closing this issue due to:
- lack of response
- lack of reproducibility
- probably a Hedgedoc issue

Feel free to open this issue again if you still encounter issues.

**Closed by JJ-8** 2022-12-05 09:27 UTC
